IF OBJECT_ID ('TABELA DE NUMEROS','U') IS NOT NULL
	DROP TABLE [TABELA DE NUMERO]

CREATE TABLE [TABELA DE NUMERO] ([NUMERO] INT, [STATUS] VARCHAR(200))

DECLARE @LIMITE_MINIMO INT
DECLARE @LIMITE_MAXIMO INT
DECLARE @CONTADOR_NOTAS INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 100000

SET NOCOUNT ON
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN

	SELECT @CONTADOR_NOTAS = COUNT(*) 
		FROM [NOTAS FISCAIS]
			WHERE [NUMERO] = @LIMITE_MINIMO

	IF @CONTADOR_NOTAS > 0
		INSERT INTO [TABELA DE NUMERO] ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'É nota fiscal') 
	ELSE
		INSERT INTO [TABELA DE NUMERO] ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'Não é nota fiscal') 
  
	SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1
	
END