CREATE FUNCTION listaNotasCliente (@CPF AS VARCHAR(12)) RETURNS TABLE AS RETURN SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF

SELECT * FROM [dbo].[listaNotasCliente]('1471156710')


SELECT A.CPF, A.NUM_NOTA, B.TOTAL_FATURAMENTO
FROM
(SELECT CPF, (SELECT COUNT(*) 
	FROM [dbo].[listaNotasCliente](CPF)) AS NUM_NOTA
		FROM [TABELA DE CLIENTES]) A
INNER JOIN
(SELECT CPF, SUM([dbo].[FaturamentoNota](NUMERO)) AS TOTAL_FATURAMENTO
	FROM [NOTAS FISCAIS] GROUP BY CPF) B
		ON A.CPF = B.CPF