SELECT * FROM [TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END
FROM
[TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END AS CLASSIFICA,
AVG([PREÇO DE LISTA]) AS MEDIA
FROM
[TABELA DE PRODUTOS]
GROUP BY [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END

SELECT YEAR([DATA]), COUNT(*) FROM [NOTAS FISCAIS] GROUP BY YEAR(DATA)

-------------------------------------------------------------------------------------------

SELECT [NOME],
	CASE WHEN YEAR([DATA DE NASCIMENTO]) < 1990 THEN 'ADULTO'
	WHEN YEAR([DATA DE NASCIMENTO]) BETWEEN 1990 AND  1995 THEN 'JOVENS'
	ELSE 'CRIANÇAS' END
	FROM [TABELA DE CLIENTES]