SELECT * FROM [TABELA DE VENDEDORES]

SELECT * FROM [NOTAS FISCAIS]

SELECT * FROM [TABELA DE VENDEDORES] INNER JOIN 
[NOTAS FISCAIS] ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA

SELECT * FROM [TABELA DE VENDEDORES] A INNER JOIN 
[NOTAS FISCAIS] B ON A.MATRICULA = B.MATRICULA

SELECT VEN.MATRICULA, VEN.[NOME], COUNT(*) 
	FROM [TABELA DE VENDEDORES] VEN
	INNER JOIN 
	[NOTAS FISCAIS] FI 
		ON VEN.MATRICULA = FI.MATRICULA
	GROUP BY VEN.MATRICULA, VEN.[NOME]

SELECT VEN.MATRICULA, VEN.[NOME], YEAR(DATA), 
COUNT(*) 
	FROM [TABELA DE VENDEDORES] VEN 
	INNER JOIN 
	[NOTAS FISCAIS] FI 
	ON VEN.MATRICULA = FI.MATRICULA
	GROUP BY VEN.MATRICULA, VEN.[NOME], YEAR(DATA)

SELECT VEN.MATRICULA, VEN.[NOME], YEAR(DATA), COUNT(*) 
	FROM [TABELA DE VENDEDORES] VEN 
	INNER JOIN 
	[NOTAS FISCAIS] FI 
	ON VEN.MATRICULA = FI.MATRICULA
	GROUP BY VEN.MATRICULA, VEN.[NOME], YEAR(DATA)
	ORDER BY YEAR(DATA), VEN.[NOME]

-------------------------------------------------------------------------------------------

SELECT * FROM [TABELA DE VENDEDORES] INNER JOIN 
[NOTAS FISCAIS] ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA

SELECT * FROM [TABELA DE VENDEDORES], [NOTAS FISCAIS]     --INNER JOIN ANTIGO
WHERE [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA 