SELECT * 
	FROM [TABELA DE CLIENTES] 
	INNER JOIN [NOTAS FISCAIS] 
	ON [TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF

SELECT * FROM [TABELA DE CLIENTES]

SELECT CL.[NOME], COUNT(*) 
	FROM [TABELA DE CLIENTES] CL 
	INNER JOIN [NOTAS FISCAIS] NF 
	ON CL.CPF = NF.CPF
GROUP BY CL.[NOME]

SELECT CL.[NOME], COUNT(*) 
	FROM [TABELA DE CLIENTES] CL 
	LEFT JOIN [NOTAS FISCAIS] NF 
	ON CL.CPF = NF.CPF
GROUP BY CL.[NOME]

SELECT CL.[CPF], CL.[NOME], COUNT(*) 
	FROM [TABELA DE CLIENTES] CL 
	LEFT JOIN [NOTAS FISCAIS] NF 
	ON CL.CPF = NF.CPF
GROUP BY  CL.[CPF], CL.[NOME]

SELECT * FROM [NOTAS FISCAIS] WHERE CPF = '95939180787'

SELECT CL.[NOME], NF.[MATRICULA] 
	FROM [TABELA DE CLIENTES] CL 
	LEFT JOIN [NOTAS FISCAIS] NF
	ON CL.CPF = NF.CPF

SELECT DISTINCT CL.[NOME], NF.[MATRICULA] 
	FROM [TABELA DE CLIENTES] CL 
	LEFT JOIN [NOTAS FISCAIS] NF
	ON CL.CPF = NF.CPF

SELECT DISTINCT CL.[NOME], NF.[MATRICULA] 
	FROM [NOTAS FISCAIS] NF
	RIGHT JOIN [TABELA DE CLIENTES] CL
	ON CL.CPF = NF.CPF