DECLARE @LIMITE_MINIMO INT
DECLARE @LIMITE_MAXIMO INT
DECLARE @CONTADOR_NOTAS INT
DECLARE @TABELA_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR(200))
CREATE TABLE #TABELA_NUMERO2 ([NUMERO] INT, [STATUS] VARCHAR(200))

SET @LIMITE_MINIMO = 98
SET @LIMITE_MAXIMO = 103

SET NOCOUNT ON
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN

	SELECT @CONTADOR_NOTAS = COUNT(*) 
		FROM [NOTAS FISCAIS]
			WHERE [NUMERO] = @LIMITE_MINIMO

	IF @CONTADOR_NOTAS > 0
		BEGIN
			INSERT INTO @TABELA_NUMEROS ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'É nota fiscal') 
			INSERT INTO #TABELA_NUMERO2 ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'É nota fiscal') 
		END
	ELSE
		BEGIN
			INSERT INTO @TABELA_NUMEROS ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'Não é nota fiscal') 
			INSERT INTO #TABELA_NUMERO2 ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'Não é nota fiscal') 
		END
  
	SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1
	
END

SELECT * FROM @TABELA_NUMEROS
SELECT * FROM #TABELA_NUMERO2