CREATE PROCEDURE RetornaValores
@CPF AS VARCHAR(12),
@ANO AS INT,
@NUM_NOTAS AS INT OUTPUT,
@FATURAMENTO AS FLOAT OUTPUT

AS

BEGIN

	SELECT @NUM_NOTAS = COUNT (*) 
	FROM [NOTAS FISCAIS] 
		WHERE CPF = @CPF AND YEAR([DATA]) = @ANO

	SELECT @FATURAMENTO = SUM (QUANTIDADE * [PREÇO]) 
	FROM [ITENS NOTAS FISCAIS] B
	INNER JOIN [NOTAS FISCAIS] A ON A.NUMERO = B.NUMERO
		WHERE CPF = @CPF AND YEAR([DATA]) = @ANO

END


DECLARE @NUM_NOTAS INT
DECLARE @FATURAMENTO FLOAT
DECLARE @CPF VARCHAR (12)
DECLARE @ANO INT

SET @CPF = '19290992743'
SET @ANO = 2016

EXEC RetornaValores @CPF = @CPF, @ANO = @ANO, @NUM_NOTAS = @NUM_NOTAS OUTPUT, @FATURAMENTO = @FATURAMENTO OUTPUT

SELECT @NUM_NOTAS, @FATURAMENTO