CREATE PROCEDURE [dbo].[BuscaPorEntidadesEX] @ENTIDADE AS VARCHAR(10)
AS
BEGIN
IF @ENTIDADE = 'CLIENTES'
	SELECT [CPF] AS IDENTIFICADOR, [NOME] AS DESCRITOR, [BAIRRO] AS BAIRRO
		FROM [TABELA DE CLIENTES]
ELSE IF @ENTIDADE = 'VENDEDORES'
	SELECT [MATRICULA] AS IDENTIFICADOR, [NOME] AS DESCRITOR, [BAIRRO] AS BAIRRO
		FROM [TABELA DE VENDEDORES]
END
GO

EXEC BuscaPorEntidadesEX 'CLIENTES'

----------------------------------------------------------------------------------

ALTER PROCEDURE [dbo].[BuscaPorEntidadesEX] @ENTIDADE AS VARCHAR(10)
AS
BEGIN
IF @ENTIDADE = 'CLIENTES'
	SELECT [CPF] AS IDENTIFICADOR, [NOME] AS DESCRITOR
		FROM [TABELA DE CLIENTES]
ELSE IF @ENTIDADE = 'VENDEDORES'
	SELECT [MATRICULA] AS IDENTIFICADOR, [NOME] AS DESCRITOR
		FROM [TABELA DE VENDEDORES]
END
GO

EXEC BuscaPorEntidadesEX 'CLIENTES'

--------------------------------------------------------------------------

IF OBJECT_ID ('BuscaPorEntidadesEX', 'P') IS NOT NULL
DROP PROCEDURE BuscaPorEntidadesEX


