DECLARE @NOME VARCHAR(200)
DECLARE CURSOR1 CURSOR FOR SELECT TOP 4 NOME FROM [TABELA DE CLIENTES]

OPEN CURSOR1

FETCH NEXT FROM CURSOR1 INTO @NOME

BEGIN
	PRINT @NOME
	FETCH NEXT FROM CURSOR1 INTO @NOME
END 